[tox]
envlist =
    py310-django{42,50}-djangorestframework{314}{,-pytest}
    py{311}-django{42}-djangorestframework{314}{,-pytest}
    py{310,311,312,313}-django{50}-djangorestframework{315,316,317}{,-pytest}
    py{310,311,312,313}-django{51}-djangorestframework{315,316,317}{,-pytest}
    py{310,311,312,313}-django{52}-djangorestframework{315,316,317,318}{,-pytest}
    py{312,313}-django{60}-djangorestframework{317,318}{,-pytest}
    py{312,313}-django{61}-djangorestframework{318}{,-pytest}
    py310-django42-djangorestframework314-djangofilter235
    py311-django51-djangorestframework317-djangofilter251
    py312-django{52,60,61}-djangorestframework318-djangofilter261

[testenv]
usedevelop = true
setenv =
    DJANGO_SETTINGS_MODULE=settings
    ; Hack: use an environment var to specify the test runner (to avoid using
    ; "nopytest" as a factor).
    DRFG_TEST_RUNNER=./tests/manage.py test
    pytest: DRFG_TEST_RUNNER=-m pytest
commands =
    coverage run {env:DRFG_TEST_RUNNER} {posargs:tests/django_restframework_gis_tests}

deps =
    django42: Django~=4.2.0
    django50: Django~=5.0.0
    django51: Django~=5.1.0
    django52: Django~=5.2.0
    django60: Django~=6.0.0
    django61: Django~=6.1.0
    djangorestframework314: djangorestframework~=3.14.0
    djangorestframework315: djangorestframework~=3.15.0
    djangorestframework316: djangorestframework~=3.16.0
    djangorestframework317: djangorestframework~=3.17.0
    djangorestframework318: djangorestframework~=3.18.0
    djangofilter235: django-filter~=23.5
    djangofilter251: django-filter~=25.1
    djangofilter261: django-filter~=26.1
    -rrequirements-test.txt
    pytest: pytest
    pytest: pytest-django

[flake8]
exclude = .tox
