# Generated by Django 5.1.5 on 2025-01-24 17:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_restframework_gis_tests", "0004_auto_20240228_2357"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherSridLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("slug", models.SlugField(blank=True, max_length=128, unique=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=31287),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
