name: Stale PR Management
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: read
  issues: write
  pull-requests: write
concurrency:
  group: bot-autoassign-stale-pr-${{ github.repository }}
  cancel-in-progress: false
jobs:
  manage-stale-prs-python:
    uses: openwisp/openwisp-utils/.github/workflows/reusable-bot-autoassign.yml@master
    with:
      bot_command: stale_pr
    secrets:
      OPENWISP_BOT_APP_ID: ${{ secrets.OPENWISP_BOT_APP_ID }}
      OPENWISP_BOT_PRIVATE_KEY: ${{ secrets.OPENWISP_BOT_PRIVATE_KEY }}
